package com.rideaustin.test.asserts.helpers;

public enum EmailType {
  RIDER_SIGNUP,
  DRIVER_SIGNUP,
  PASSWORD_RESET,
  USER_DISABLED,
  USER_ENABLED,
  USER_DEACTIVATED,
  USER_ACTIVATED,
  RIDER_TRIP_SUMMARY,
  RIDER_TRIP_CANCELLED,
  DRIVER_EARNINGS,
  DRIVER_CUSTOM_EARNINGS,
  CARD_LOCKED,
  PAYMENT_DECLINED,

}
